/*
  KI-Modell-Atlas — Datenbasis
  Stand der Recherche: 4. Juli 2026 (quellengeprüft)

  Preise: USD pro 1 Mio. Token (Eingabe / Ausgabe), sofern nicht anders vermerkt.
  Quellen: offizielle Anbieter-Preisseiten (openai.com/api/pricing,
  anthropic.com/pricing, ai.google.dev/pricing, api-docs.deepseek.com,
  mistral.ai/pricing, docs.x.ai, Alibaba Cloud Model Studio), gegengeprüft
  über aipricing.guru (Stand Anfang Juli 2026).

  WICHTIG (ehrlich): Nicht jedes Modell hat einen öffentlichen Token-Preis.
  Bild-, Audio- und Video-Modelle rechnen anders ab (pro Bild/Sekunde/Zeichen).
  Open-Weight-Modelle sind kostenlos selbst hostbar; ihr API-Preis hängt vom
  Anbieter ab. Noch nicht veröffentlichte Modelle haben keinen Preis. In diesen
  Fällen steht ein ehrlicher Hinweis statt einer erfundenen Zahl.

  Felder je Modell:
    name, type, status, flagship?, note (Kurznotiz),
    preis   – String: Token-Preis oder ehrlicher Hinweis
    kontext – String: Kontextfenster / Ausgabegrenze oder "—"
    lizenz  – String: z. B. "proprietär (API)", "Open-Weight (Apache 2.0)"
    staerken – Array kurzer Stichpunkte
    einsatz  – String: typischer Einsatzzweck
    detail   – String: längerer Erklärtext
*/

window.KI_ATLAS_META = {
  stand: "4. Juli 2026",
  hinweis: "Statischer, quellengeprüfter Stand. Preise können sich ändern — im Zweifel die offizielle Anbieterseite prüfen.",
  preishinweis: "Preise in USD pro 1 Mio. Token (Eingabe / Ausgabe), sofern nicht anders angegeben.",
};

window.KI_ATLAS_DATA = [
  {
    id: "openai",
    name: "OpenAI",
    land: "USA",
    produkt: "ChatGPT",
    farbe: "#10a37f",
    links: {
      modelle: "https://platform.openai.com/docs/models",
      news: "https://openai.com/news/",
      web: "https://openai.com/",
      preise: "https://openai.com/api/pricing/",
    },
    modelle: [
      {
        name: "GPT-5.5", type: "text", flagship: true, status: "ga",
        note: "Allgemein verfügbares Flaggschiff für Reasoning & Coding",
        preis: "$5 / $30", kontext: "≈ 1,05 Mio. Token", lizenz: "proprietär (API)",
        staerken: ["Starkes Reasoning", "Sehr gutes Coding", "Native Computer-Nutzung"],
        einsatz: "Anspruchsvolle Entwicklung, komplexe Agenten, professionelle Wissensarbeit.",
        detail: "GPT-5.5 ist OpenAIs allgemein verfügbares Spitzenmodell (Stand Juli 2026). Es vereint hohe Reasoning-Tiefe mit sehr guter Code-Qualität und ist der empfohlene Standard für schwierige Aufgaben. Über ChatGPT ist es das stärkste Modell für zahlende Nutzer; über die API der Standard für neue anspruchsvolle Anwendungen.",
      },
      {
        name: "GPT-5.5 Pro", type: "text", status: "ga",
        note: "Höchste Präzision, teuerste Variante",
        preis: "$30 / $180", kontext: "≈ 1,05 Mio. Token", lizenz: "proprietär (API)",
        staerken: ["Maximale Reasoning-Tiefe", "Höchste Zuverlässigkeit"],
        einsatz: "Teure, aber besonders wichtige Aufgaben, bei denen Fehler viel kosten.",
        detail: "Die Pro-Variante von GPT-5.5 ist auf maximale Präzision bei den schwersten Problemen ausgelegt. Sie ist deutlich teurer und wird gezielt für hochwertige, fehlerkritische Arbeit eingesetzt — nicht als Alltagsmodell.",
      },
      {
        name: "GPT-5.6 Sol / Terra / Luna", type: "text", status: "preview",
        note: "Neueste Familie, eingeschränkte Preview (API/Codex, ~20 Partner)",
        preis: "Sol $5 / $30 · Terra $2.50 / $15 · Luna $1 / $6 (Preview)", kontext: "je nach Variante",
        lizenz: "proprietär (Preview, eingeschränkt)",
        staerken: ["Sol: Frontier-Reasoning & Agenten", "Terra: günstig, GPT-5.5-nah", "Luna: sehr schnell & billig"],
        einsatz: "Frühzugang für ausgewählte Partner; noch nicht allgemein verfügbar.",
        detail: "GPT-5.6 ist OpenAIs neueste Familie (Ende Juni 2026 als begrenzte Preview gestartet, zunächst nur über API/Codex für rund 20 Partnerorganisationen). Sol ist das Flaggschiff für Frontier-Reasoning und lange agentische Aufgaben, Terra die günstige Allround-Variante, Luna die schnellste und billigste. Allgemeine Verfügbarkeit war angekündigt, aber noch nicht erfolgt.",
      },
      {
        name: "GPT-5.4", type: "text", status: "ga",
        note: "Günstigeres Frontier-Modell; + mini / nano",
        preis: "$2.50 / $15 · mini $0.75 / $4.50 · nano $0.20 / $1.25", kontext: "≈ 1 Mio. Token",
        lizenz: "proprietär (API)",
        staerken: ["Gutes Preis-Leistungs-Verhältnis", "Skalierbare Größen (mini/nano)"],
        einsatz: "Allgemeine Produktion, hohe Volumen, Routing in Multi-Agent-Systemen.",
        detail: "GPT-5.4 bleibt als günstigere Frontier-Familie aktiv. Die mini- und nano-Varianten sind für schnelle, kostensensible Aufgaben (Klassifizierung, Extraktion, hohe Durchsätze) gedacht, während das Basismodell eine starke Allround-Wahl zu moderatem Preis ist.",
      },
      {
        name: "GPT-5.3 Instant", type: "text", status: "ga",
        note: "Schneller Standard in ChatGPT",
        preis: "kein separater API-Einzelpreis (ChatGPT-Standard)", kontext: "—",
        lizenz: "proprietär (in ChatGPT)",
        staerken: ["Sehr schnell", "Automatisches Umschalten zu Reasoning"],
        einsatz: "Alltags-Chat in ChatGPT; wechselt bei Bedarf selbst auf tieferes Denken.",
        detail: "GPT-5.3 Instant ist der schnelle Standard im ChatGPT-Router und schaltet automatisch auf tieferes Reasoning um, wenn eine Anfrage es braucht. Ein eigener API-Token-Preis wird dafür nicht separat ausgewiesen; die Abrechnung läuft über die ChatGPT-Pläne.",
      },
      {
        name: "GPT-Image (in GPT-5.x)", type: "image", status: "ga",
        note: "Bilderzeugung integriert in die GPT-5-Familie",
        preis: "pro Bild abgerechnet (kein Token-Preis)", kontext: "—",
        lizenz: "proprietär (API)",
        staerken: ["In die GPT-5-Familie integriert", "Gute Prompt-Treue"],
        einsatz: "Bilderzeugung direkt aus dem Chat- bzw. API-Kontext.",
        detail: "Die Bildfähigkeiten sind in die GPT-5-Familie integriert. Die Abrechnung erfolgt pro erzeugtem Bild (abhängig von Auflösung/Qualität), nicht pro Token — deshalb hier kein Token-Preis. Aktuelle Sätze stehen auf der offiziellen Preisseite.",
      },
      {
        name: "Sora (Video)", type: "video", status: "ga",
        note: "Text-zu-Video (separates Produkt)",
        preis: "Video — separate Abrechnung (kein Token-Preis)", kontext: "—",
        lizenz: "proprietär (Produkt/API)",
        staerken: ["Text-zu-Video", "Hohe visuelle Qualität"],
        einsatz: "Videoerzeugung aus Textbeschreibungen.",
        detail: "Sora ist OpenAIs Text-zu-Video-System und wird als eigenes Produkt abgerechnet (nach Länge/Auflösung), nicht pro Token. Verfügbarkeit und Preise richten sich nach dem jeweiligen Sora-Angebot.",
      },
    ],
  },
  {
    id: "google",
    name: "Google DeepMind",
    land: "USA",
    produkt: "Gemini",
    farbe: "#4285f4",
    links: {
      modelle: "https://ai.google.dev/gemini-api/docs/models",
      news: "https://blog.google/technology/ai/",
      web: "https://deepmind.google/",
      preise: "https://ai.google.dev/pricing",
    },
    modelle: [
      {
        name: "Gemini 3.5 Flash", type: "multi", flagship: true, status: "ga",
        note: "Neuester breit verfügbarer Release (Mai 2026), nahe Pro-Niveau",
        preis: "$1.50 / $9.00", kontext: "1 Mio. Token", lizenz: "proprietär (API)",
        staerken: ["Nahe Pro-Niveau bei Flash-Tempo", "Sehr gutes Coding & Agenten", "1M-Kontext"],
        einsatz: "Produktions-Pipelines, lange Dokumente, agentische Workflows zu moderatem Preis.",
        detail: "Gemini 3.5 Flash (Mai 2026) ist Googles neuester breit verfügbarer Release und bringt nahezu Pro-Niveau bei Flash-typischem Tempo und Preis. Für viele Aufgaben, die früher ein Pro-Modell brauchten, ist 3.5 Flash der neue Startpunkt — stark bei Coding, langen Kontexten und parallelen Agenten.",
      },
      {
        name: "Gemini 3.5 Pro", type: "multi", status: "preview",
        note: "Neues Premium-Reasoning-Flaggschiff, im Rollout",
        preis: "Preview — Preis noch nicht offiziell gelistet", kontext: "1 Mio. Token (erwartet)",
        lizenz: "proprietär (Preview)",
        staerken: ["Höchste Reasoning-Tiefe der Gemini-Linie", "Multimodal"],
        einsatz: "Anspruchsvollstes Reasoning, sobald allgemein verfügbar.",
        detail: "Gemini 3.5 Pro ist das angekündigte Premium-Reasoning-Flaggschiff und befindet sich im Rollout. Ein offizieller Listenpreis lag zum RechercheStand noch nicht vor — daher hier bewusst kein Preis, sondern der Hinweis auf die Preview-Phase.",
      },
      {
        name: "Gemini 3.1 Pro", type: "multi", status: "ga",
        note: "Starkes Reasoning-Modell, großer Kontext",
        preis: "$2 / $12 (bis 200K) · darüber $4 / $18", kontext: "bis 2 Mio. Token",
        lizenz: "proprietär (API)",
        staerken: ["Sehr großer, stabiler Kontext", "Starkes Reasoning", "Gute Multimodalität"],
        einsatz: "Codebasis-weite Analysen, sehr lange Dokumente, komplexes Reasoning.",
        detail: "Gemini 3.1 Pro ist ein starkes Reasoning-Modell mit einem der größten zuverlässig nutzbaren Kontextfenster am Markt. Bei Prompts über 200K Token steigt der Token-Preis. Besonders geeignet, wenn sehr viele Dateien oder lange Texte konsistent verarbeitet werden müssen.",
      },
      {
        name: "Gemini 3.1 Flash-Lite", type: "multi", status: "ga",
        note: "Günstigste, schnellste Stufe",
        preis: "$0.25 / $1.50", kontext: "1 Mio. Token", lizenz: "proprietär (API)",
        staerken: ["Sehr günstig", "Sehr schnell", "1M-Kontext"],
        einsatz: "Hochvolumige, kostensensible Aufgaben (Klassifizierung, Routing, Extraktion).",
        detail: "Flash-Lite ist die günstigste und schnellste Stufe der Gemini-Familie, optimiert für hohe Durchsätze bei niedrigen Kosten — bei weiterhin sehr großem Kontextfenster.",
      },
      {
        name: "Gemini Omni", type: "video", status: "preview",
        note: "Video-Generierung & -Editing aus beliebigem Input",
        preis: "Video — separate Abrechnung (kein Token-Preis)", kontext: "—",
        lizenz: "proprietär (Preview)",
        staerken: ["Video aus Text/Bild/Audio/Video", "Führend bei Videoverständnis"],
        einsatz: "Videoerzeugung und -bearbeitung, multimodale Inhalte.",
        detail: "Gemini Omni erzeugt und bearbeitet Video aus beliebigem Input (Bild, Audio, Video, Text) und gilt bei nativem Videoverständnis als führend. Als Generativ-Media-Modell wird es nicht pro Token abgerechnet, sondern nach Ausgabe (Länge/Auflösung).",
      },
      {
        name: "Nano Banana 2 (3.1 Flash Image)", type: "image", status: "ga",
        note: "Bildgenerierung/-editing",
        preis: "pro Bild abgerechnet (kein Token-Preis)", kontext: "—",
        lizenz: "proprietär (API)",
        staerken: ["Sehr gutes Textrendering im Bild", "Konversationelles Editing"],
        einsatz: "Produktionsreife Bilderzeugung und -bearbeitung.",
        detail: "Nano Banana 2 (offiziell Gemini 3.1 Flash Image) ist Googles Bildmodell mit starker Instruktionstreue und Textrendering. Abgerechnet wird pro erzeugtem Bild, nicht pro Token.",
      },
      {
        name: "Gemini 3.1 Flash TTS", type: "audio", status: "ga",
        note: "Steuerbare Sprachsynthese",
        preis: "Audio — separate Abrechnung (kein Token-Preis)", kontext: "—",
        lizenz: "proprietär (API)",
        staerken: ["Fein steuerbare Stimme (Tempo, Tonhöhe)", "Lange Inhalte"],
        einsatz: "Sprachsynthese für Podcasts, Vorlesen, Barrierefreiheit.",
        detail: "Gemini 3.1 Flash TTS ist Googles steuerbares Text-zu-Sprache-Modell mit natürlicher Prosodie. Die Abrechnung erfolgt audio-/zeichenbasiert, nicht pro Token.",
      },
      {
        name: "Gemma 4", type: "text", status: "ga",
        note: "Offenes Modell (Open-Weight)",
        preis: "Open-Weight — kostenlos selbst hostbar (API-Preis je Anbieter)", kontext: "128K+ Token",
        lizenz: "Open-Weight (Gemma-Lizenz)",
        staerken: ["Frei herunterladbar", "Für Reasoning & Agenten ausgelegt", "Multimodal"],
        einsatz: "Selbst-Hosting, Feintuning, datenschutzsensible Umgebungen.",
        detail: "Gemma 4 ist Googles offene Modellfamilie (April 2026), die man kostenlos herunterladen, feintunen und selbst betreiben kann. Ein Token-Preis entsteht nur, wenn man es über einen Cloud-Anbieter nutzt — beim Self-Hosting fallen nur die eigenen Infrastrukturkosten an.",
      },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    land: "USA",
    produkt: "Claude",
    farbe: "#d97757",
    links: {
      modelle: "https://platform.claude.com/docs/en/about-claude/models/overview",
      news: "https://www.anthropic.com/news",
      web: "https://www.anthropic.com/",
      preise: "https://www.anthropic.com/pricing",
    },
    modelle: [
      {
        name: "Claude Fable 5", type: "text", flagship: true, status: "ga",
        note: "Fähigstes öffentliches Modell; Sicherheits-Routing auf Opus 4.8",
        preis: "$10 / $50", kontext: "1 Mio. Token · Ausgabe bis 128K", lizenz: "proprietär (API)",
        staerken: ["Höchste Fähigkeit im öffentlichen Angebot", "Sehr präzise Instruktionstreue", "Adaptives Denken"],
        einsatz: "Lange, hochkomplexe Aufgaben, bei denen Mehrleistung die Mehrkosten rechtfertigt.",
        detail: "Claude Fable 5 ist Anthropics fähigstes öffentlich verfügbares Modell (Mythos-Klasse). Für bestimmte sensible Themen (u. a. Cybersicherheit, Biologie) leiten Sicherheits-Klassifikatoren die Anfrage automatisch an Claude Opus 4.8 um. Sinnvoll bei langlaufenden, fehlerkritischen Aufgaben mit hohem Wert.",
      },
      {
        name: "Claude Opus 4.8", type: "text", status: "ga",
        note: "Arbeitspferd für komplexe Aufgaben & agentisches Coding",
        preis: "$5 / $25", kontext: "1 Mio. Token", lizenz: "proprietär (API)",
        staerken: ["Sehr stark im Coding", "Zuverlässig für Agenten", "Zero-Data-Retention möglich"],
        einsatz: "Standard für anspruchsvolle Entwicklung und autonome Agenten.",
        detail: "Claude Opus 4.8 ist das zuverlässige Arbeitspferd für ernsthafte Arbeit — der empfohlene Standard für die meisten API-Anwendungen und für Claude Code, wenn man nicht die volle Fable-5-Leistung braucht. Unterstützt Zero-Data-Retention, was Fable 5 nicht bietet.",
      },
      {
        name: "Claude Sonnet 5", type: "text", status: "ga",
        note: "Standard für Alltag & Entwicklung",
        preis: "Sonnet-Tier ≈ $3 / $15 (Sonnet 5 ggf. abweichend — offizielle Seite prüfen)",
        kontext: "1 Mio. Token", lizenz: "proprietär (API)",
        staerken: ["Nahe Opus-Intelligenz zu Sonnet-Preis", "Sehr agentisch", "Treibt Terminals & Browser"],
        einsatz: "Alltags-Entwicklung und der Großteil der Agenten-Aufgaben.",
        detail: "Claude Sonnet 5 (30. Juni 2026) ist der neue Standard auf Free und Pro und bringt nahezu Opus-Intelligenz zum Sonnet-Preis. Hinweis zur Ehrlichkeit: Der Sonnet-Tier lag zuletzt bei $3/$15 (Sonnet 4.6); ein separat gelisteter Sonnet-5-Preis lag zum Rechercheszeitpunkt noch nicht vor — im Zweifel die offizielle Preisseite prüfen.",
      },
      {
        name: "Claude Haiku 4.5", type: "text", status: "ga",
        note: "Schnell & günstig",
        preis: "$1 / $5", kontext: "200K Token · Ausgabe bis 64K", lizenz: "proprietär (API)",
        staerken: ["Sehr schnell", "Günstig", "Nahe Frontier-Qualität für die Größe"],
        einsatz: "Klassifizierung, Zusammenfassung, Support, hohe Durchsätze.",
        detail: "Claude Haiku 4.5 ist das schnelle, günstige Modell der Familie — geeignet für hochvolumige, latenzsensible Aufgaben. Kleineres Kontextfenster (200K) als die größeren Modelle, dafür deutlich billiger.",
      },
      {
        name: "Claude Mythos 5", type: "text", status: "limited",
        note: "Nur Trusted Access / Project Glasswing",
        preis: "$10 / $50 (nur Trusted Access)", kontext: "1 Mio. Token", lizenz: "proprietär (eingeschränkt)",
        staerken: ["Gleiche Fähigkeitsklasse wie Fable 5", "Ohne bestimmte Sicherheits-Weichen"],
        einsatz: "Nur für geprüfte Organisationen im Project Glasswing.",
        detail: "Claude Mythos 5 teilt die Fähigkeitsklasse von Fable 5, jedoch ohne bestimmte Sicherheits-Klassifikatoren. Es ist nicht allgemein verfügbar, sondern nur über Trusted Access (Project Glasswing) für ausgewählte Organisationen.",
      },
    ],
  },
  {
    id: "meta",
    name: "Meta",
    land: "USA",
    produkt: "Llama / Meta AI",
    farbe: "#06b6d4",
    links: {
      modelle: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/",
      news: "https://ai.meta.com/blog/",
      web: "https://ai.meta.com/",
      preise: "https://ai.meta.com/",
    },
    modelle: [
      {
        name: "Llama 4 (Scout / Maverick)", type: "multi", flagship: true, status: "ga",
        note: "Nativ multimodale Open-Weight-Linie",
        preis: "Open-Weight — kostenlos selbst hostbar (API-Preis je Anbieter)", kontext: "sehr großer Kontext",
        lizenz: "Open-Weight (Llama-Lizenz)",
        staerken: ["Nativ multimodal", "Frei herunterladbar", "Zwei Größen (Scout/Maverick)"],
        einsatz: "Self-Hosting, Feintuning, Aufbau eigener Produkte auf offener Basis.",
        detail: "Llama 4 (Scout und Maverick) ist Metas nativ multimodale, offene Modell-Linie. Die Gewichte sind frei verfügbar; man kann selbst hosten oder über Cloud-Anbieter (AWS, Azure, u. a.) nutzen — der Token-Preis hängt dann vom jeweiligen Anbieter ab, nicht von Meta direkt.",
      },
      {
        name: "Meta Muse Spark", type: "text", status: "ga",
        note: "Metas erstes proprietäres Closed-Weight-Modell, nur auf meta.ai",
        preis: "nur über meta.ai — kein öffentlicher API-Token-Preis", kontext: "—",
        lizenz: "proprietär (Closed-Weight)",
        staerken: ["Metas erstes geschlossenes Modell", "Von Meta Superintelligence Labs"],
        einsatz: "Nutzung ausschließlich über meta.ai (keine herunterladbaren Gewichte).",
        detail: "Meta Muse Spark (April 2026) ist Metas erstes proprietäres Closed-Weight-Modell — ein Bruch mit der bisherigen Open-Source-Strategie. Es ist nur auf meta.ai nutzbar, ohne herunterladbare Gewichte und ohne öffentlich gelisteten API-Token-Preis.",
      },
    ],
  },
  {
    id: "xai",
    name: "xAI",
    land: "USA",
    produkt: "Grok",
    farbe: "#e11d48",
    links: {
      modelle: "https://x.ai/news",
      news: "https://x.ai/news",
      web: "https://x.ai/",
      preise: "https://docs.x.ai/docs/models",
    },
    modelle: [
      {
        name: "Grok 4.3 beta", type: "multi", flagship: true, status: "preview",
        note: "Aktuelles Flaggschiff (Beta), mit Sprach-/Bild-/Video-Verständnis",
        preis: "$1.25 / $2.50", kontext: "256K Token", lizenz: "proprietär (Beta)",
        staerken: ["Starkes agentisches Tool-Calling", "Niedrige Halluzinationsrate", "Multimodal"],
        einsatz: "Reasoning, Recherche, komplexe Dokumenten-Workflows in Echtzeit.",
        detail: "Grok 4.3 beta ist xAIs aktuelles Flaggschiff (Early Beta, für ausgewählte Abonnenten) mit verbessertem Reasoning, agentischem Tool-Calling und multimodalem Verständnis (Sprache, Bild, Video). Wissensstand bis Dezember 2025; laufend verfeinert.",
      },
      {
        name: "Grok Build 0.1 / V9-Medium", type: "text", status: "preview",
        note: "Coding-Modelle",
        preis: "Grok Build 0.1: $1 / $2 · V9-Medium: kein Listenpreis", kontext: "256K Token",
        lizenz: "proprietär (Beta)",
        staerken: ["Auf agentisches Coding ausgelegt", "Immer-an-Reasoning", "Text- & Bildeingabe"],
        einsatz: "Coding-Agenten im Terminal/IDE, längere Implementierungsaufgaben.",
        detail: "Grok Build 0.1 ist xAIs dediziertes Coding-Modell (öffentliche Beta seit Mai 2026) mit 256K-Kontext, Immer-an-Reasoning sowie Text- und Bildeingabe. V9-Medium (1,5 Bio. Parameter, auf Cursor-Daten trainiert) ist ein weiteres Coding-Modell; ein öffentlicher Token-Preis war dafür nicht gelistet.",
      },
      {
        name: "Grok Voice", type: "audio", status: "ga",
        note: "Gesprochene Interaktion",
        preis: "Audio — separate Abrechnung (kein Token-Preis)", kontext: "—",
        lizenz: "proprietär (App/API)",
        staerken: ["Gesprochene Interaktion in Echtzeit"],
        einsatz: "Sprachdialog mit Grok in der mobilen App.",
        detail: "Grok Voice (Juni 2026) bringt gesprochene Interaktion in die Grok-App. Als Sprachfunktion wird es nicht pro Text-Token abgerechnet; Verfügbarkeit und Konditionen richten sich nach dem jeweiligen Grok-Angebot.",
      },
      {
        name: "Grok Imagine 1.5", type: "video", status: "preview",
        note: "Bild-zu-Video mit nativem Audio",
        preis: "Video — separate Abrechnung (kein Token-Preis)", kontext: "—",
        lizenz: "proprietär (Preview/API)",
        staerken: ["Bild-zu-Video", "Natives Audio in einem Durchgang"],
        einsatz: "Kurze, cineastische Videoclips aus Standbildern.",
        detail: "Grok Imagine 1.5 (Preview, API-Zugang seit Juni 2026) erzeugt aus einem Standbild flüssige Videoclips und generiert dabei Audio (Musik, Effekte, Lippensynchronität) im selben Durchgang. Abrechnung video-/clipbasiert, nicht pro Token.",
      },
      {
        name: "Grok 5", type: "text", status: "training",
        note: "6T-Parameter angekündigt, noch nicht öffentlich (Q2-Fenster verstrichen)",
        preis: "noch nicht veröffentlicht — kein Preis", kontext: "—", lizenz: "—",
        staerken: ["Angekündigt: 6 Bio. Parameter (MoE)", "Nativ multimodal (geplant)"],
        einsatz: "Noch nicht nutzbar — in Training/Vorbereitung.",
        detail: "Grok 5 ist angekündigt (rund 6 Bio. Parameter, Mixture-of-Experts), war zum Rechercheszeitpunkt aber noch nicht öffentlich verfügbar — das ursprüngliche Q2-2026-Fenster ist verstrichen. Deshalb bewusst kein Preis und keine gesicherten Spezifikationen, nur der ehrliche Status.",
      },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    land: "China",
    produkt: "DeepSeek",
    farbe: "#6d4aff",
    links: {
      modelle: "https://api-docs.deepseek.com/",
      news: "https://api-docs.deepseek.com/news/",
      web: "https://www.deepseek.com/",
      preise: "https://api-docs.deepseek.com/quick_start/pricing",
    },
    modelle: [
      {
        name: "DeepSeek V4-Pro", type: "text", flagship: true, status: "preview",
        note: "1,6T MoE (49B aktiv), 1M-Kontext, offene Gewichte (MIT); offizielle GA Mitte Juli",
        preis: "$0.435 / $0.87", kontext: "1 Mio. Token · Ausgabe bis 384K", lizenz: "Open-Weight (MIT)",
        staerken: ["Sehr günstig für die Leistung", "Offene Gewichte (MIT)", "Starkes Coding & Reasoning"],
        einsatz: "Inferenz-lastige Produktion, Self-Hosting, kostensensible Frontier-Arbeit.",
        detail: "DeepSeek V4-Pro (1,6 Bio. Parameter MoE, 49 Mrd. aktiv) ist ein offen lizenziertes (MIT) Frontier-Modell mit 1M-Kontext und außergewöhnlich niedrigem Token-Preis. Zum Rechercheszeitpunkt als Preview gelistet, offizielle GA für Mitte Juli angekündigt. Spricht OpenAI- und Anthropic-API-Format.",
      },
      {
        name: "DeepSeek V4-Flash", type: "text", status: "preview",
        note: "284B MoE (13B aktiv), günstig & schnell",
        preis: "$0.14 / $0.28", kontext: "1 Mio. Token · Ausgabe bis 384K", lizenz: "Open-Weight (MIT)",
        staerken: ["Extrem günstig", "Schnell", "Offene Gewichte (MIT)"],
        einsatz: "Hochvolumige Agenten-Schleifen, Drafting, Iteration.",
        detail: "DeepSeek V4-Flash (284 Mrd. Parameter MoE, 13 Mrd. aktiv) ist die schnelle, sehr günstige Variante mit gleichem 1M-Kontext. Reasoning nahe der Pro-Version bei größerem Denk-Budget. Ideal für hohe Durchsätze zu minimalen Kosten.",
      },
      {
        name: "DeepSeek R1", type: "text", status: "ga",
        note: "Reasoning-Linie (Vorgänger)",
        preis: "gering (Open-Weight; frühere API-Sätze ≈ $0.55 / $2.19)", kontext: "128K Token",
        lizenz: "Open-Weight (MIT)",
        staerken: ["Etablierte Reasoning-Linie", "Frei herunterladbar", "Gut untersucht"],
        einsatz: "Bestehende R1-Deployments, Feintuning eines Reasoning-Modells.",
        detail: "DeepSeek R1 ist die bekannte Reasoning-Linie (Vorgänger der V4-Ära). Offen lizenziert (MIT) und frei hostbar; für neue Produktions-Workloads ist meist V4 die stärkere und günstigere Wahl, R1 bleibt als stabiler, gut untersuchter Checkpoint relevant.",
      },
      {
        name: "Janus-Pro-7B", type: "image", status: "ga",
        note: "Text-zu-Bild / multimodale Generierung",
        preis: "Open-Weight — kostenlos selbst hostbar", kontext: "—", lizenz: "Open-Weight (MIT)",
        staerken: ["Text-zu-Bild", "Kompakt (7B)", "Frei herunterladbar"],
        einsatz: "Bilderzeugung und multimodale Generierung im Self-Hosting.",
        detail: "Janus-Pro-7B ist DeepSeeks kompaktes, offen lizenziertes Modell für Text-zu-Bild und multimodale Generierung. Frei herunterladbar; es fallen nur eigene Infrastrukturkosten an.",
      },
      {
        name: "DeepSeek VL2", type: "image", status: "ga",
        note: "OCR & Dokumentenverständnis (Vision)",
        preis: "Open-Weight — kostenlos selbst hostbar", kontext: "—", lizenz: "Open-Weight (MIT)",
        staerken: ["OCR", "Dokumenten- & Diagramm-Verständnis", "Frei herunterladbar"],
        einsatz: "OCR, Diagramme, Dokumenten-Frage-Antwort.",
        detail: "DeepSeek VL2 ist das offen lizenzierte Vision-Modell für OCR und Dokumentenverständnis (Diagramme, Belege, Dokument-QA). Frei hostbar; keine Token-Gebühr beim Self-Hosting.",
      },
    ],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    land: "Frankreich",
    produkt: "Le Chat / Mistral",
    farbe: "#fa5211",
    links: {
      modelle: "https://docs.mistral.ai/models/overview",
      news: "https://mistral.ai/news/",
      web: "https://mistral.ai/",
      preise: "https://mistral.ai/pricing",
    },
    modelle: [
      {
        name: "Mistral Medium 3.5", type: "multi", flagship: true, status: "preview",
        note: "Erstes zusammengeführtes Flaggschiff (Instruct+Reasoning+Code), 128B dense, Open-Weight",
        preis: "$1.50 / $7.50", kontext: "256K Token", lizenz: "Open-Weight (modifiziert MIT)",
        staerken: ["Instruktion, Reasoning & Code in einem Modell", "Konfigurierbare Reasoning-Tiefe", "Self-Host auf wenigen GPUs"],
        einsatz: "Standard-Flaggschiff für Entwicklung, Agenten und Unternehmensautomatisierung.",
        detail: "Mistral Medium 3.5 ist Mistrals erstes zusammengeführtes Flaggschiff — Instruktionsbefolgung, Reasoning und Coding in einem dichten 128B-Modell (öffentliche Preview). Als Open-Weight (modifiziert MIT) auf wenigen GPUs selbst hostbar; Reasoning-Aufwand pro Anfrage konfigurierbar. Standard in Mistral Vibe und Le Chat.",
      },
      {
        name: "Mistral Large 3", type: "multi", status: "ga",
        note: "Großes Open-Weight-MoE (675B total / 41B aktiv), Apache 2.0",
        preis: "Open-Weight (Apache 2.0) — API-Preis variiert je Anbieter", kontext: "256K Token",
        lizenz: "Open-Weight (Apache 2.0)",
        staerken: ["Großes MoE (675B/41B aktiv)", "Frei lizenziert (Apache 2.0)", "Multimodal & mehrsprachig"],
        einsatz: "Anspruchsvolle Produktion, lange Dokumente, EU-Datenresidenz.",
        detail: "Mistral Large 3 ist Mistrals großes Open-Weight-MoE (675 Mrd. total, 41 Mrd. aktiv) unter Apache 2.0 — frei nutz- und anpassbar. Ein einheitlicher Token-Listenpreis existiert nicht: Beim Self-Hosting zahlt man Infrastruktur, über die Plattform/Cloud-Anbieter richtet sich der Preis nach diesem.",
      },
      {
        name: "Mistral Small 4", type: "multi", status: "ga",
        note: "Effizient, konfigurierbare Reasoning-Tiefe",
        preis: "$0.10 / $0.30", kontext: "256K Token", lizenz: "Open-Weight (Apache 2.0)",
        staerken: ["Sehr günstig", "Multimodal", "Reasoning ein-/ausschaltbar"],
        einsatz: "Kostensensible Produktion, schnelle Prototypen, hohe Volumen.",
        detail: "Mistral Small 4 vereint Reasoning, Multimodalität und Coding in einem effizienten Modell (119B total, ~6B aktiv) mit einstellbarer Reasoning-Tiefe. Sehr günstig und offen lizenziert (Apache 2.0) — eine der preiswertesten multimodalen Optionen.",
      },
      {
        name: "Voxtral TTS", type: "audio", status: "ga",
        note: "Sprachsynthese mit Voice-Cloning",
        preis: "$0.016 pro 1.000 Zeichen (kein Token-Preis)", kontext: "—",
        lizenz: "Open-Weight (CC BY-NC 4.0; kommerziell separat)",
        staerken: ["Voice-Cloning ab wenigen Sekunden", "9 Sprachen", "Sehr niedrige Latenz"],
        einsatz: "Sprachassistenten, Vertonung, Kundendialog.",
        detail: "Voxtral TTS ist Mistrals offenes Text-zu-Sprache-Modell mit Zero-Shot-Voice-Cloning (ab ~3 s Referenz) und 9 Sprachen. Abrechnung zeichenbasiert ($0.016/1.000 Zeichen). Lizenz CC BY-NC 4.0 (nicht-kommerziell); kommerzielle Nutzung erfordert eine separate Vereinbarung.",
      },
      {
        name: "OCR 4", type: "image", status: "ga",
        note: "Dokumenten-OCR (Document AI)",
        preis: "seitenbasierte Abrechnung (kein Token-Preis)", kontext: "—",
        lizenz: "proprietär (API)",
        staerken: ["OCR mit Absatz-Boxen", "Strukturierte Blocklabels"],
        einsatz: "Dokumentenverarbeitung, strukturierte Extraktion.",
        detail: "OCR 4 ist Mistrals aktueller OCR-Dienst (Document-AI-Stack) mit Absatz-Bounding-Boxen und strukturierten Blocklabels. Abgerechnet wird pro Seite/Dokument, nicht pro Token.",
      },
    ],
  },
  {
    id: "qwen",
    name: "Alibaba (Qwen)",
    land: "China",
    produkt: "Qwen",
    farbe: "#d946ef",
    links: {
      modelle: "https://www.alibabacloud.com/help/en/model-studio/models",
      news: "https://qwen.ai/research",
      web: "https://qwen.ai/",
      preise: "https://www.alibabacloud.com/help/en/model-studio/models",
    },
    modelle: [
      {
        name: "Qwen3.7-Max", type: "text", flagship: true, status: "ga",
        note: "Neues proprietäres Flaggschiff, 1M-Kontext, API-only",
        preis: "$2.50 / $7.50 · Cache-Input $0.25", kontext: "1 Mio. Token", lizenz: "proprietär (API-only)",
        staerken: ["Frontier-nahe Leistung günstig", "1M-Kontext", "Sehr lange autonome Läufe"],
        einsatz: "Langlaufende Agenten, Repository-Analyse, günstiges Frontier-Reasoning.",
        detail: "Qwen3.7-Max ist Alibabas neuestes proprietäres Flaggschiff (Mai 2026), API-only mit 1M-Kontext. Deutlich günstiger als GPT- oder Claude-Alternativen bei frontier-naher Leistung; demonstriert wurden sehr lange autonome Agentenläufe. Spricht auch das Anthropic-API-Protokoll (nutzbar mit Claude-Tools).",
      },
      {
        name: "Qwen3.7-Plus", type: "multi", status: "ga",
        note: "Multimodale Agent-Variante",
        preis: "≈ 1/6 der Max-Kosten (multimodal)", kontext: "1 Mio. Token", lizenz: "proprietär (API)",
        staerken: ["Multimodal", "Deutlich günstiger als Max", "Agentisch"],
        einsatz: "Multimodale Agenten zu niedrigem Preis.",
        detail: "Qwen3.7-Plus ist die multimodale Agent-Variante der 3.7-Familie zu rund einem Sechstel der Max-Token-Kosten. Für multimodale, agentische Aufgaben, bei denen Preis wichtiger ist als die absolute Spitzenleistung.",
      },
      {
        name: "Qwen3.5 (397B-A17B)", type: "multi", status: "ga",
        note: "Open-Weight (Apache 2.0), 201 Sprachen",
        preis: "Open-Weight — kostenlos selbst hostbar (API-Preis je Anbieter)", kontext: "großer Kontext",
        lizenz: "Open-Weight (Apache 2.0)",
        staerken: ["Frei lizenziert (Apache 2.0)", "201 Sprachen", "Nativ multimodal"],
        einsatz: "Self-Hosting, Mehrsprachigkeit, datensouveräne Umgebungen.",
        detail: "Qwen3.5 (397 Mrd. Parameter MoE, 17 Mrd. aktiv) ist das offen lizenzierte Flaggschiff (Apache 2.0, Februar 2026) mit Unterstützung für 201 Sprachen und nativer Multimodalität. Frei herunterladbar und selbst hostbar; der Token-Preis entsteht nur bei Nutzung über einen Cloud-Anbieter.",
      },
      {
        name: "Qwen3.5-Omni", type: "multi", status: "ga",
        note: "Text, Bild, Audio & Video in einem Modell",
        preis: "Open-Weight — kostenlos selbst hostbar (je nach Variante)", kontext: "großer Kontext",
        lizenz: "Open-Weight",
        staerken: ["Alle vier Modalitäten in einem Modell", "Sprach- und Videoeingabe"],
        einsatz: "Multimodale Anwendungen (z. B. Sprache + Bildschirm) im Self-Hosting.",
        detail: "Qwen3.5-Omni versteht Text, Bild, Audio und Video nativ in einem Modell und ermöglicht Szenarien wie „per Sprache beschreiben und per Video zeigen“. Offen verfügbar; keine Token-Gebühr beim Self-Hosting.",
      },
      {
        name: "Wan / Qwen-Image 2.0", type: "image", status: "ga",
        note: "Bildgenerierung mit Textrendering",
        preis: "Bild — separate Abrechnung (kein Token-Preis)", kontext: "—",
        lizenz: "proprietär / je nach Variante",
        staerken: ["Fotorealistische Bilder", "Präzises mehrzeiliges Textrendering"],
        einsatz: "Bilderzeugung mit exaktem Text (Überschriften, Branding).",
        detail: "Wan bzw. Qwen-Image 2.0 erzeugt fotorealistische Bilder mit besonders präzisem, mehrzeiligem Textrendering. Als Bildmodell erfolgt die Abrechnung pro Bild, nicht pro Token.",
      },
      {
        name: "Qwen3-TTS", type: "audio", status: "ga",
        note: "Sprachsynthese mit Voice-Cloning",
        preis: "Audio — separate Abrechnung (kein Token-Preis)", kontext: "—",
        lizenz: "offene Lizenz / je nach Variante",
        staerken: ["Voice-Cloning", "Streaming-Generierung"],
        einsatz: "Vertonung, Sprachassistenten.",
        detail: "Qwen3-TTS ist Alibabas Sprachsynthese mit Voice-Cloning und Streaming-Ausgabe für Vorlesen und Sprachassistenten. Abrechnung audio-/zeichenbasiert, nicht pro Token.",
      },
    ],
  },
];

/* Weitere Anbieter — bewusst nur eine Kurzliste (Anbieter + bekannte
   Modellfamilien), ohne Preis-/Detailprüfung. Ehrlicher Hinweis dazu
   steht auf der Seite. Reihenfolge: grob nach Bedeutung/Bekanntheit. */
window.KI_ATLAS_WEITERE = [
  { name: "Microsoft",          land: "USA",         modelle: "MAI-Familie · Phi-4 (offen) · Copilot-Integrationen",
    web: "https://microsoft.ai/",
    info: "Microsoft entwickelt unter der Marke Microsoft AI die eigene MAI-Modellfamilie sowie die offenen Phi-Modelle und den KI-Assistenten Copilot." },
  { name: "Amazon (AWS)",       land: "USA",         modelle: "Nova-Familie (Micro / Lite / Pro / Premier)",
    web: "https://aws.amazon.com/ai/generative-ai/nova/",
    info: "Amazon bietet über AWS die Nova-Modellfamilie an, schnelle multimodale Basismodelle für Text und Bild in mehreren Größen (Micro, Lite, Pro, Premier)." },
  { name: "NVIDIA",             land: "USA",         modelle: "Nemotron-Familie (offen)",
    web: "https://www.nvidia.com/en-us/ai-data-science/foundation-models/nemotron/",
    info: "NVIDIA veröffentlicht die offene Nemotron-Modellfamilie mit Trainingsdaten und Gewichten, ausgelegt auf effiziente, agentische KI-Anwendungen." },
  { name: "IBM",                land: "USA",         modelle: "Granite-Familie (offen)",
    web: "https://www.ibm.com/granite",
    info: "IBM entwickelt die offene Granite-Modellfamilie für Unternehmen: Sprach-, Code-, Vision- und Guardrail-Modelle unter Apache-2.0-Lizenz." },
  { name: "Apple",              land: "USA",         modelle: "Apple Foundation Models (auf dem Ger\u00e4t, in iOS/macOS)",
    web: "https://www.apple.com/apple-intelligence/",
    info: "Apple integriert unter Apple Intelligence eigene Foundation Models direkt in iPhone, iPad und Mac, mit Schwerpunkt auf datenschutzfreundlicher Verarbeitung auf dem Ger\u00e4t." },
  { name: "Cohere",             land: "Kanada",      modelle: "Command-Familie (A / R)",
    web: "https://cohere.com/command",
    info: "Cohere richtet sich an Unternehmen und bietet die Command-Modellfamilie (u. a. Command A und R) für agentische, mehrsprachige KI-Anwendungen." },
  { name: "AI21 Labs",          land: "Israel",      modelle: "Jamba-Familie",
    web: "https://www.ai21.com/jamba/",
    info: "AI21 Labs entwickelt die offene Jamba-Modellfamilie, die eine hybride Mamba-Transformer-Architektur für lange Kontexte nutzt." },
  { name: "Perplexity",         land: "USA",         modelle: "Sonar-Familie (Suche/Antworten)",
    web: "https://www.perplexity.ai/api-platform/",
    info: "Perplexity betreibt eine KI-Antwortmaschine und entwickelt die Sonar-Modelle, die Websuche mit generierten, quellengestützten Antworten verbinden." },
  { name: "Reka",               land: "USA",         modelle: "Reka Core / Flash",
    web: "https://www.reka.ai/",
    info: "Reka entwickelt nativ multimodale Modelle wie Reka Core und Flash, die Text, Bild, Audio und Video verarbeiten." },
  { name: "Moonshot AI",        land: "China",       modelle: "Kimi-Familie (K2)",
    web: "https://www.moonshot.ai/",
    info: "Moonshot AI aus China entwickelt die Kimi-Modellfamilie, darunter das offene Modell Kimi K2 mit langem Kontext." },
  { name: "Zhipu AI / Z.ai",    land: "China",       modelle: "GLM-Familie",
    web: "https://z.ai/model-api",
    info: "Z.ai (früher Zhipu AI) aus China entwickelt die GLM-Modellfamilie für Reasoning, Programmieren und agentische Aufgaben, teils als Open-Weight." },
  { name: "MiniMax",            land: "China",       modelle: "MiniMax-M-Familie",
    web: "https://www.minimax.io/",
    info: "MiniMax aus China entwickelt multimodale KI-Modelle, darunter die Sprachmodellreihe MiniMax-M sowie Modelle für Sprache, Video und Musik." },
  { name: "ByteDance",          land: "China",       modelle: "Doubao / Seed-Familie",
    web: "https://seed.bytedance.com/",
    info: "ByteDance entwickelt über sein Seed-Forschungsteam die Doubao- und Seed-Modellfamilien, die den KI-Assistenten Doubao und die Volcano-Engine-Plattform antreiben." },
  { name: "Baidu",              land: "China",       modelle: "ERNIE-Familie",
    web: "https://ernie.baidu.com/",
    info: "Baidu entwickelt die ERNIE-Modellfamilie, multimodale Basismodelle, die den chinesischen KI-Chatbot ERNIE Bot (früher Wenxin Yiyan) antreiben." },
  { name: "Tencent",            land: "China",       modelle: "Hunyuan-Familie",
    web: "https://hunyuan.tencent.com/",
    info: "Tencent entwickelt die Hunyuan-Modellfamilie mit Modellen für Text, Bild und 3D, teils als Open-Weight veröffentlicht." },
  { name: "Black Forest Labs",  land: "Deutschland", modelle: "FLUX-Familie (Bild)",
    web: "https://bfl.ai/",
    info: "Black Forest Labs aus Deutschland entwickelt die FLUX-Modellfamilie zur KI-Bildgenerierung, verfügbar per API und teils als Open-Weight." },
  { name: "Stability AI",       land: "UK",          modelle: "Stable Diffusion (Bild)",
    web: "https://stability.ai/",
    info: "Stability AI entwickelt offene generative Modelle, darunter die bekannte Bildgenerator-Familie Stable Diffusion sowie Modelle für Video, Audio und 3D." },
  { name: "Midjourney",         land: "USA",         modelle: "Midjourney (Bild)",
    web: "https://www.midjourney.com/",
    info: "Midjourney betreibt einen bekannten KI-Bildgenerator, der aus Textbeschreibungen hochwertige, stilisierte Bilder erzeugt." },
  { name: "Runway",             land: "USA",         modelle: "Gen-Familie (Video)",
    web: "https://runwayml.com/",
    info: "Runway entwickelt die Gen-Modellfamilie zur KI-Videogenerierung, die aus Text und Bildern kurze, realistische Videosequenzen erzeugt." },
  { name: "Luma AI",            land: "USA",         modelle: "Dream Machine / Ray (Video)",
    web: "https://lumalabs.ai/",
    info: "Luma AI entwickelt KI-Videomodelle, darunter Dream Machine und die Ray-Modellreihe, die aus Text und Bildern Videos erzeugen." },
  { name: "ElevenLabs",         land: "USA",         modelle: "Sprach-/Stimm-Modelle (Audio)",
    web: "https://elevenlabs.io/",
    info: "ElevenLabs entwickelt KI-Modelle für Sprachsynthese, Stimmklonen, Transkription und Musik und unterstützt dabei über 70 Sprachen." },
];

// Gesamtliste (Marktzahlen): Nutzer, Umsatz, Bewertung, Gründung — 29 Anbieter.
// Nutzer-/Umsatzzahlen sind Schätzungen bzw. Run-Rate (ARR) und nicht direkt
// vergleichbar (WAU vs. MAU). Bewertungen/Gründungsjahre am 6. Juli 2026 recherchiert.
// Leere Felder ("") bedeuten: keine belastbare, vergleichbare Zahl.
// Felder: name, land, produkt, kategorie, nutzer, metrik, umsatz, bewertung, gruendung, quelle
window.KI_ATLAS_MARKT = [
  { name: "OpenAI", land: "USA", produkt: "ChatGPT", kategorie: "Chatbot",
    nutzer: "über 1 Mrd. / 900 Mio. WAU", metrik: "MAU (App) / wöchentl.",
    umsatz: "ca. 25 Mrd. $", bewertung: "ca. 852 Mrd. $ (2026)", gruendung: "2015",
    quelle: "Sensor Tower/Reuters, OpenAI (Feb. 2026); The Information", quelleName: "Reuters", quelleUrl: "https://www.reuters.com/" },
  { name: "Anthropic", land: "USA", produkt: "Claude", kategorie: "Chatbot",
    nutzer: "ca. 8–19 Mio.", metrik: "MAU (Web)",
    umsatz: "ca. 30–47 Mrd. $", bewertung: "ca. 965 Mrd. $ (2026)", gruendung: "2021",
    quelle: "Anthropic (April 2026); Sacra (Mai 2026)", quelleName: "Anthropic", quelleUrl: "https://www.anthropic.com/news" },
  { name: "Meta", land: "USA", produkt: "Meta AI (Llama / Muse Spark)", kategorie: "Chatbot (eingebettet)",
    nutzer: "ca. 1,2 Mrd.", metrik: "MAU",
    umsatz: "— (kein separater KI-Umsatz)", bewertung: "Teil von Meta", gruendung: "2004",
    quelle: "Meta Q1-2026-Bericht", quelleName: "Meta IR", quelleUrl: "https://investor.atmeta.com/" },
  { name: "Google DeepMind", land: "USA", produkt: "Gemini", kategorie: "Chatbot",
    nutzer: "über 900 Mio.", metrik: "MAU (App)",
    umsatz: "— (in Google-Umsatz enthalten)", bewertung: "Teil von Alphabet", gruendung: "2010",
    quelle: "Google I/O (Mai 2026)", quelleName: "Google Blog", quelleUrl: "https://blog.google/" },
  { name: "Microsoft", land: "USA", produkt: "Copilot (MAI / Phi-4)", kategorie: "Chatbot (eingebettet)",
    nutzer: "ca. 420 Mio.", metrik: "MAU (alle Oberflächen)",
    umsatz: "— (in Microsoft-Umsatz enthalten)", bewertung: "Teil von Microsoft", gruendung: "1975",
    quelle: "Business of Apps / Microsoft (2026)", quelleName: "Business of Apps", quelleUrl: "https://www.businessofapps.com/data/microsoft-copilot-statistics/" },
  { name: "ByteDance", land: "China", produkt: "Doubao / Seed", kategorie: "Chatbot",
    nutzer: "ca. 345 Mio.", metrik: "MAU",
    umsatz: "", bewertung: "ca. 550 Mrd. $ (2026, privat)", gruendung: "2012",
    quelle: "QuestMobile (März 2026)", quelleName: "QuestMobile", quelleUrl: "https://www.questmobile.com.cn/" },
  { name: "Baidu", land: "China", produkt: "ERNIE (Ernie Bot)", kategorie: "Chatbot + Modelle",
    nutzer: "ca. 220 Mio.", metrik: "MAU",
    umsatz: "", bewertung: "Teil von Baidu", gruendung: "2000",
    quelle: "The Capital Review / Medium (Mai 2026)", quelleName: "The Capital Review", quelleUrl: "https://medium.com/@TheCapitalReview" },
  { name: "Alibaba", land: "China", produkt: "Qwen / Tongyi", kategorie: "Chatbot + offene Modelle",
    nutzer: "ca. 200 Mio.", metrik: "MAU (App)",
    umsatz: "", bewertung: "Teil von Alibaba", gruendung: "1999",
    quelle: "AICPB (Jan. 2026), via France24", quelleName: "France24", quelleUrl: "https://www.france24.com/" },
  { name: "Tencent", land: "China", produkt: "Hunyuan / Yuanbao", kategorie: "Chatbot + Modelle",
    nutzer: "ca. 150 Mio.", metrik: "MAU (Yuanbao)",
    umsatz: "", bewertung: "Teil von Tencent", gruendung: "1998",
    quelle: "The Capital Review / Medium (Mai 2026)", quelleName: "The Capital Review", quelleUrl: "https://medium.com/@TheCapitalReview" },
  { name: "Perplexity", land: "USA", produkt: "Perplexity (Sonar)", kategorie: "KI-Suche",
    nutzer: "ca. 34 Mio. / über 100 Mio.", metrik: "MAU (Kern / alle Produkte)",
    umsatz: "ca. 0,5 Mrd. $", bewertung: "ca. 20 Mrd. $ (2025)", gruendung: "2022",
    quelle: "gradually.ai, Sacra/FT (April 2026)", quelleName: "gradually.ai", quelleUrl: "https://gradually.ai/" },
  { name: "DeepSeek", land: "China", produkt: "DeepSeek", kategorie: "Chatbot + offene Modelle",
    nutzer: "ca. 97 Mio.", metrik: "MAU",
    umsatz: "", bewertung: "ca. 50–59 Mrd. $ (2026)", gruendung: "2023",
    quelle: "AICPB (April 2026); ElectroIQ", quelleName: "ElectroIQ", quelleUrl: "https://electroiq.com/" },
  { name: "xAI", land: "USA", produkt: "Grok", kategorie: "Chatbot",
    nutzer: "ca. 64 Mio.", metrik: "MAU",
    umsatz: "— (nicht offengelegt)", bewertung: "ca. 230 Mrd. $ (2026)", gruendung: "2023",
    quelle: "DemandSage (2026)", quelleName: "DemandSage", quelleUrl: "https://www.demandsage.com/" },
  { name: "Mistral AI", land: "Frankreich", produkt: "Le Chat / Mistral", kategorie: "Chatbot + offene Modelle",
    nutzer: "unter 45 Mio.", metrik: "monatl. aktiv (EU-Empfänger)",
    umsatz: "über 0,4 Mrd. $ (Ziel: über 1 Mrd.)", bewertung: "ca. 11,7 Mrd. € (2025)", gruendung: "2023",
    quelle: "Mistral-Angabe (2026), via getpanto.ai", quelleName: "getpanto.ai", quelleUrl: "https://getpanto.ai/" },
  { name: "Moonshot AI", land: "China", produkt: "Kimi (K2)", kategorie: "Chatbot + offene Modelle",
    nutzer: "ca. 10–15 Mio. (Höchst. 36 Mio.)", metrik: "MAU (Kimi-App)",
    umsatz: "über 0,2 Mrd. $ (ARR)", bewertung: "ca. 20 Mrd. $ (2026)", gruendung: "2023",
    quelle: "QuestMobile/Statista; TechCrunch (Mai 2026)", quelleName: "TechCrunch", quelleUrl: "https://techcrunch.com/" },
  { name: "Zhipu AI / Z.ai", land: "China", produkt: "GLM / Qingyan", kategorie: "Chatbot + offene Modelle",
    nutzer: "ca. 3–9 Mio.", metrik: "MAU (Consumer-App)",
    umsatz: "", bewertung: "börsennotiert (HKEX); ~6,6 Mrd. $ (2025, privat)", gruendung: "2019",
    quelle: "36kr (Nov. 2025); Bamboo Works/AICPB (2025)", quelleName: "36Kr", quelleUrl: "https://36kr.com/" },
  { name: "MiniMax", land: "China", produkt: "MiniMax-M / Xingye / Talkie", kategorie: "Chatbot + Modelle (Multimedia)",
    nutzer: "", metrik: "",
    umsatz: "", bewertung: "börsennotiert (HKEX); ~14 Mrd. $ (2026)", gruendung: "2022",
    quelle: "börsennotiert (Hongkong, Jan. 2026); keine belastbare MAU", quelleName: "HKEXnews", quelleUrl: "https://www.hkexnews.hk/" },
  { name: "Midjourney", land: "USA", produkt: "Midjourney", kategorie: "Bildgenerator",
    nutzer: "ca. 20 Mio. (registriert, Discord)", metrik: "registrierte Nutzer",
    umsatz: "ca. 0,5 Mrd. $", bewertung: "— (gebootstrappt)", gruendung: "2021",
    quelle: "Sacra; The Information (März 2026); DemandSage", quelleName: "Sacra", quelleUrl: "https://sacra.com/" },
  { name: "ElevenLabs", land: "USA", produkt: "Sprach-/Stimm-Modelle", kategorie: "Audiogenerator",
    nutzer: "", metrik: "",
    umsatz: "über 0,33 Mrd. $", bewertung: "11 Mrd. $ (2026)", gruendung: "2022",
    quelle: "TechCrunch / Bloomberg (Jan. 2026)", quelleName: "TechCrunch", quelleUrl: "https://techcrunch.com/" },
  { name: "Runway", land: "USA", produkt: "Gen-Familie", kategorie: "Videogenerator",
    nutzer: "", metrik: "",
    umsatz: "— (nicht offengelegt)", bewertung: "5,3 Mrd. $ (2026)", gruendung: "2018",
    quelle: "Sacra (Feb. 2026)", quelleName: "Sacra", quelleUrl: "https://sacra.com/" },
  { name: "Luma AI", land: "USA", produkt: "Dream Machine / Ray", kategorie: "Videogenerator",
    nutzer: "", metrik: "",
    umsatz: "", bewertung: "ca. 4 Mrd. $ (2025)", gruendung: "2021",
    quelle: "CNBC (Nov. 2025)", quelleName: "CNBC", quelleUrl: "https://www.cnbc.com/" },
  { name: "Black Forest Labs", land: "Deutschland", produkt: "FLUX-Familie", kategorie: "Bildgenerator (Modelle)",
    nutzer: "", metrik: "",
    umsatz: "", bewertung: "3,25 Mrd. $ (2025)", gruendung: "2024",
    quelle: "TechCrunch (Dez. 2025)", quelleName: "TechCrunch", quelleUrl: "https://techcrunch.com/" },
  { name: "Stability AI", land: "UK", produkt: "Stable Diffusion", kategorie: "Bildgenerator",
    nutzer: "", metrik: "",
    umsatz: "— (nicht durchgängig offengelegt)", bewertung: "ca. 1 Mrd. $ (2024)", gruendung: "2019",
    quelle: "Primärrunde (Juni 2024)" },
  { name: "Cohere", land: "Kanada", produkt: "Command-Familie (A / R)", kategorie: "Modelle (Enterprise/API)",
    nutzer: "", metrik: "",
    umsatz: "— (nicht durchgängig offengelegt)", bewertung: "ca. 7 Mrd. $ (2025)", gruendung: "2019",
    quelle: "TechCrunch/Bloomberg (Sept. 2025)", quelleName: "TechCrunch", quelleUrl: "https://techcrunch.com/" },
  { name: "AI21 Labs", land: "Israel", produkt: "Jamba-Familie", kategorie: "Modelle (Enterprise/API)",
    nutzer: "", metrik: "",
    umsatz: "", bewertung: "ca. 1,4 Mrd. $ (2025)", gruendung: "2017",
    quelle: "Calcalist/Tracxn (Mai 2025)", quelleName: "Calcalist", quelleUrl: "https://www.calcalist.co.il/" },
  { name: "Reka", land: "USA", produkt: "Reka Core / Flash", kategorie: "Modelle (Enterprise/API)",
    nutzer: "", metrik: "",
    umsatz: "", bewertung: "ca. 1 Mrd. $ (2025)", gruendung: "2022",
    quelle: "SiliconAngle (Juli 2025)", quelleName: "SiliconAngle", quelleUrl: "https://siliconangle.com/" },
  { name: "NVIDIA", land: "USA", produkt: "Nemotron-Familie (offen)", kategorie: "Offene Modelle",
    nutzer: "", metrik: "",
    umsatz: "— (kein separater Modell-Umsatz)", bewertung: "Teil von NVIDIA", gruendung: "1993",
    quelle: "" },
  { name: "Amazon (AWS)", land: "USA", produkt: "Nova-Familie (Micro / Lite / Pro / Premier)", kategorie: "Modelle (Cloud/API)",
    nutzer: "", metrik: "",
    umsatz: "— (in AWS-Umsatz enthalten)", bewertung: "Teil von Amazon", gruendung: "1994",
    quelle: "" },
  { name: "IBM", land: "USA", produkt: "Granite-Familie (offen)", kategorie: "Offene Modelle (Enterprise/API)",
    nutzer: "", metrik: "",
    umsatz: "", bewertung: "Teil von IBM", gruendung: "1911",
    quelle: "" },
  { name: "Apple", land: "USA", produkt: "Apple Foundation Models (on-device)", kategorie: "Eingebettete Modelle (iOS/macOS)",
    nutzer: "", metrik: "",
    umsatz: "", bewertung: "Teil von Apple", gruendung: "1976",
    quelle: "" },
];

